# Generated by Django 5.2.17 on 2026-08-13 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('nutritionist')), _negated=True), name='athlete_user_differs_from_nutritionist')],
            },
        ),
    ]
