"""
Django settings for kcal_setup project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from os import getenv
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Always load the environment file from the backend directory, regardless of
# the directory from which manage.py is executed.
load_dotenv(BASE_DIR / '.env')

ENVIRONMENT = getenv('DJANGO_ENVIRONMENT', 'development').lower()

FRONTEND_URL = getenv('FRONTEND_URL', 'http://localhost:5173').rstrip('/')
ATHLETE_INVITATION_EXPIRY_HOURS = int(
    getenv('ATHLETE_INVITATION_EXPIRY_HOURS', '48')
)
ATHLETE_INVITATION_EXPOSE_LINK = getenv(
    'ATHLETE_INVITATION_EXPOSE_LINK', str(ENVIRONMENT == 'development')
).lower() in {'1', 'true', 'yes'}
if ENVIRONMENT != 'development' and ATHLETE_INVITATION_EXPOSE_LINK:
    raise RuntimeError('Invitation links cannot be exposed outside development.')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if ENVIRONMENT != 'development':
        raise RuntimeError('DJANGO_SECRET_KEY is required outside development.')
    SECRET_KEY = 'django-insecure-development-only-key'

JWT_SIGNING_KEY = getenv('JWT_SIGNING_KEY')
if not JWT_SIGNING_KEY:
    if ENVIRONMENT != 'development':
        raise RuntimeError('JWT_SIGNING_KEY is required outside development.')
    JWT_SIGNING_KEY = 'jwt-development-only-key-separate-from-django'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes'}

ALLOWED_HOSTS = [
    host.strip()
    for host in getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'apps.accounts',
    'apps.athletes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kcal_setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kcal_setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': getenv('DB_NAME'),
        'USER': getenv('DB_USER'),
        'PASSWORD': getenv('DB_PASSWORD'),
        'HOST': getenv('DB_HOST', 'localhost'),
        'PORT': getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

SESSION_COOKIE_SECURE = getenv(
    'SESSION_COOKIE_SECURE', str(ENVIRONMENT != 'development')
).lower() in {'1', 'true', 'yes'}
CSRF_COOKIE_SECURE = getenv(
    'CSRF_COOKIE_SECURE', str(ENVIRONMENT != 'development')
).lower() in {'1', 'true', 'yes'}
CSRF_COOKIE_SAMESITE = getenv('CSRF_COOKIE_SAMESITE', 'Lax')
SECURE_SSL_REDIRECT = getenv(
    'SECURE_SSL_REDIRECT', str(ENVIRONMENT != 'development')
).lower() in {'1', 'true', 'yes'}
SECURE_HSTS_SECONDS = int(
    getenv('SECURE_HSTS_SECONDS', '0' if ENVIRONMENT == 'development' else '31536000')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = getenv(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS', str(ENVIRONMENT != 'development')
).lower() in {'1', 'true', 'yes'}
SECURE_HSTS_PRELOAD = getenv(
    'SECURE_HSTS_PRELOAD', str(ENVIRONMENT != 'development')
).lower() in {'1', 'true', 'yes'}

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'apps.accounts.api.exceptions.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': getenv('THROTTLE_RATE_ANONYMOUS', '100/hour'),
        'user': getenv('THROTTLE_RATE_AUTHENTICATED', '1000/hour'),
        'auth_login': getenv('THROTTLE_RATE_AUTH_LOGIN', '5/minute'),
        'token_refresh': getenv('THROTTLE_RATE_TOKEN_REFRESH', '10/minute'),
        'sensitive': getenv('THROTTLE_RATE_SENSITIVE', '10/minute'),
        'athlete_invitation_issue': getenv(
            'THROTTLE_RATE_INVITATION_ISSUE', '5/hour'
        ),
        'athlete_invitation_validate': getenv(
            'THROTTLE_RATE_INVITATION_VALIDATE', '20/minute'
        ),
        'athlete_invitation_activate': getenv(
            'THROTTLE_RATE_INVITATION_ACTIVATE', '5/minute'
        ),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(getenv('JWT_ACCESS_MINUTES', '5'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(getenv('JWT_REFRESH_DAYS', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SIGNING_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JWT_REFRESH_COOKIE_NAME = getenv('JWT_REFRESH_COOKIE_NAME', 'ppn_refresh')
JWT_REFRESH_COOKIE_SECURE = getenv(
    'JWT_REFRESH_COOKIE_SECURE', str(ENVIRONMENT != 'development')
).lower() in {'1', 'true', 'yes'}
JWT_REFRESH_COOKIE_SAMESITE = getenv('JWT_REFRESH_COOKIE_SAMESITE', 'Lax')
JWT_REFRESH_COOKIE_PATH = '/api/v1/auth/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'
